# Generated by Django 3.2.25 on 2024-06-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
    ]
