# Generated by Django 3.2.25 on 2024-05-05 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240429_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationproduct',
            options={'managed': True},
        ),
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='custom_last_login',
        #     new_name='last_login',
        # ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_caution_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_caution_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rating_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_status',
            field=models.CharField(default='activate', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_user_role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_user_status',
            field=models.CharField(default='activate', max_length=10),
        ),
    ]
