# Generated by Django 3.2.25 on 2024-05-07 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240505_2339'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='user',
        #     old_name='custom_last_login',
        #     new_name='last_login',
        # ),
        migrations.AlterField(
            model_name='productreview',
            name='product_review_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product_review_rating',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
