# Generated by Django 3.2.25 on 2024-04-26 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyfunction',
            name='survey_function_rank',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='login_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comcode',
            name='com_code_grp',
            field=models.ForeignKey(db_column='com_code_grp', on_delete=django.db.models.deletion.CASCADE, to='users.comcodegrp'),
        ),
        migrations.AlterField(
            model_name='ingredientfunction',
            name='function_code',
            field=models.ForeignKey(db_column='function_code', on_delete=django.db.models.deletion.CASCADE, to='users.functioncode'),
        ),
        migrations.AlterField(
            model_name='ingredientfunction',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='function_code',
            field=models.ForeignKey(db_column='function_code', on_delete=django.db.models.deletion.CASCADE, to='users.functioncode'),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='recommendationingredient',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='recommendationingredient',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='recommendationproduct',
            name='recommendation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recommendation'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='surveyallergy',
            name='allergy_code',
            field=models.ForeignKey(db_column='allergy_code', on_delete=django.db.models.deletion.CASCADE, to='users.allergycode'),
        ),
        migrations.AlterField(
            model_name='surveyallergy',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='surveydisease',
            name='disease_code',
            field=models.ForeignKey(db_column='disease_code', on_delete=django.db.models.deletion.CASCADE, to='users.diseasecode'),
        ),
        migrations.AlterField(
            model_name='surveydisease',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='surveyfunction',
            name='function_code',
            field=models.ForeignKey(db_column='function_code', on_delete=django.db.models.deletion.CASCADE, to='users.functioncode'),
        ),
        migrations.AlterField(
            model_name='surveyfunction',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='comcode',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='allergycode',
            table='allergy_code',
        ),
    ]
