# Generated by Django 3.2.25 on 2024-05-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240507_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='custom_last_login',
            new_name='last_login',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='survey_id',
        ),
    ]
