# Generated by Django 3.2.25 on 2024-04-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240426_1418'),
        ('users', '0006_alter_user_user_password'),
    ]

    operations = [
    ]
