# Generated by Django 3.2.25 on 2024-04-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20240426_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_last',
        ),
    ]
