# Generated by Django 3.2.25 on 2024-04-27 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_login_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientfunction',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='recommendationingredient',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='users.ingredient'),
        ),
        migrations.AlterField(
            model_name='recommendationingredient',
            name='recommendation_id',
            field=models.ForeignKey(db_column='recommendation_id', on_delete=django.db.models.deletion.CASCADE, to='users.recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationproduct',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='users.product'),
        ),
        migrations.AlterField(
            model_name='recommendationproduct',
            name='recommendation_id',
            field=models.ForeignKey(db_column='recommendation_id', on_delete=django.db.models.deletion.CASCADE, to='users.recommendation'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='surveyallergy',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='surveydisease',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='surveyfunction',
            name='survey_function_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyfunction',
            name='survey_id',
            field=models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='users.survey'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
