# Generated by Django 3.2.25 on 2024-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240708_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_caution_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_function_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
