# Generated by Django 3.2.25 on 2024-04-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='user_id',
            new_name='user',
        ),
    ]
