# Generated by Django 3.2.25 on 2024-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240708_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product_review_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
