# Generated by Django 3.2.25 on 2024-04-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user_id',
        ),
    ]
