# Generated by Django 3.2.25 on 2024-04-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240427_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlike',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='productlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productlog',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
    ]
