# Generated by Django 3.2.25 on 2024-07-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_productreview_product_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='product_like_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
