# Generated by Django 3.2.25 on 2024-04-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_recommendation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.user'),
            preserve_default=False,
        ),
    ]
