# Generated by Django 3.2.25 on 2024-04-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240427_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_birth',
            field=models.CharField(max_length=20),
        ),
    ]
