# Generated by Django 3.2.25 on 2024-04-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='users.user'),
        ),
    ]
