# Generated by Django 3.2.25 on 2024-04-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240427_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='productlike',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='user_id',
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
