# Generated by Django 3.2.25 on 2024-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20240427_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted_at',
            new_name='cumstom_deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='custom_created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_login',
            new_name='custom_last_login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_at',
            new_name='custom_modified_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='custom_user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='custom_user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='custom_user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='custom_user_role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='custom_user_status',
        ),
        migrations.RemoveField(
            model_name='productlike',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='user_id',
        ),
        migrations.AddField(
            model_name='productlike',
            name='custom_user_id',
            field=models.ForeignKey(db_column='custom_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_user_id',
            field=models.ForeignKey(db_column='custom_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='custom_user_id',
            field=models.ForeignKey(db_column='custom_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_user', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='custom_user_id',
            field=models.ForeignKey(db_column='custom_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
