# Generated by Django 3.2.25 on 2024-04-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240427_1016'),
        ('users', '0019_auto_20240427_1502'),
    ]

    operations = [
    ]
